-- MySQL Script generated by MySQL Workbench
-- Tue May  9 17:16:29 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema enterprisewebapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema enterprisewebapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `enterprisewebapp` DEFAULT CHARACTER SET utf8 ;
USE `enterprisewebapp` ;

-- -----------------------------------------------------
-- Table `enterprisewebapp`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`User` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `telephone` INT NULL,
  `address` VARCHAR(100) NULL,
  `name` VARCHAR(100) NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC));


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `price` DECIMAL(10,2) NULL,
  `product_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_owner` INT NOT NULL,
  `private_product` BIT(1) NULL DEFAULT 0,
  `sold` BIT(1) NULL DEFAULT 0,
  `user_buy` INT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_Product_User1_idx` (`user_owner` ASC),
  INDEX `fk_Product_User2_idx` (`user_buy` ASC),
  CONSTRAINT `fk_Product_User1`
    FOREIGN KEY (`user_owner`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_User2`
    FOREIGN KEY (`user_buy`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`LikeT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`LikeT` (
  `user_id_user` INT NOT NULL,
  `product_idproduct` INT NOT NULL,
  `like_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id_user`, `product_idproduct`),
  INDEX `fk_Like_Product` (`product_idproduct` ASC),
  INDEX `fk_Like_User` (`user_id_user` ASC),
  CONSTRAINT `fk_user_has_Product_user`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_Product_Product1`
    FOREIGN KEY (`product_idproduct`)
    REFERENCES `enterprisewebapp`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`Favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`Favorite` (
  `user_id_user` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  `favorite_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id_user`, `Product_idProduct`),
  INDEX `fk_Favorite_Product` (`Product_idProduct` ASC),
  INDEX `fk_Favorite_user` (`user_id_user` ASC),
  CONSTRAINT `fk_Favorite_user`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorite_Product`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `enterprisewebapp`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`Bookmark`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`Bookmark` (
  `user_id_user` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  `bookmark_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id_user`, `Product_idProduct`),
  INDEX `fk_Bookmark_Product` (`Product_idProduct` ASC),
  INDEX `fk_Bookmark_User` (`user_id_user` ASC),
  CONSTRAINT `fk_Bookmark_User`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bookmark_Product`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `enterprisewebapp`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`Friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`Friends` (
  `user_id_user` INT NOT NULL,
  `user_id_user_friend` INT NOT NULL,
  `friend_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id_user`, `user_id_user_friend`),
  INDEX `fk_Friend_Friend` (`user_id_user_friend` ASC),
  INDEX `fk_Friend_User` (`user_id_user` ASC),
  CONSTRAINT `fk_user_has_user_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_user_user2`
    FOREIGN KEY (`user_id_user_friend`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`Tag` (
  `idTag` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idTag`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`Product_Tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`Product_Tags` (
  `product_idProduct` INT NOT NULL,
  `tag_idTag` INT NOT NULL,
  `product_tag_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`product_idProduct`, `tag_idTag`),
  INDEX `fk_Product_has_Tag_Tag1_idx` (`tag_idTag` ASC),
  INDEX `fk_Product_has_Tag_Product1_idx` (`product_idProduct` ASC),
  CONSTRAINT `fk_Product_has_Tag_Product1`
    FOREIGN KEY (`product_idProduct`)
    REFERENCES `enterprisewebapp`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_has_Tag_Tag1`
    FOREIGN KEY (`tag_idTag`)
    REFERENCES `enterprisewebapp`.`Tag` (`idTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`User_Invitations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`User_Invitations` (
  `user_id_user` INT NOT NULL,
  `user_id_user_invited_to` INT NOT NULL,
  `invitation_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id_user`, `user_id_user_invited_to`),
  INDEX `fk_User_who_is_invited` (`user_id_user_invited_to` ASC),
  INDEX `fk_User_who_invites` (`user_id_user` ASC),
  CONSTRAINT `fk_User_has_User_User6`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_User_User7`
    FOREIGN KEY (`user_id_user_invited_to`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`Comment` (
  `user_id_user` INT NOT NULL,
  `product_idProduct` INT NOT NULL,
  `comment_text` VARCHAR(400) NULL,
  `comment_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`product_idProduct`),
  INDEX `fk_User_has_Product_Product1_idx` (`product_idProduct` ASC),
  INDEX `fk_User_has_Product_User1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_User_has_Product_User4`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Product_Product4`
    FOREIGN KEY (`product_idProduct`)
    REFERENCES `enterprisewebapp`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`Following`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`Following` (
  `user_id_user` INT NOT NULL,
  `user_id_user_following_to` INT NOT NULL,
  `following_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id_user`, `user_id_user_following_to`),
  INDEX `fk_User_who_is_followed` (`user_id_user_following_to` ASC),
  INDEX `fk_User_who_follows` (`user_id_user` ASC),
  CONSTRAINT `fk_User_has_User_User3`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_User_User4`
    FOREIGN KEY (`user_id_user_following_to`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`groups` (
  `idgroup` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(300) NULL,
  `user_id_user` INT NOT NULL,
  `group_create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idgroup`, `user_id_user`),
  INDEX `fk_groups_User1_idx` (`user_id_user` ASC),
  CONSTRAINT `fk_groups_User1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`group_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`group_product` (
  `group_idgroup` INT NOT NULL,
  `product_idProduct` INT NOT NULL,
  PRIMARY KEY (`group_idgroup`, `product_idProduct`),
  INDEX `fk_group_has_Product_Product1_idx` (`product_idProduct` ASC),
  INDEX `fk_group_has_Product_group1_idx` (`group_idgroup` ASC),
  CONSTRAINT `fk_group_has_Product_group1`
    FOREIGN KEY (`group_idgroup`)
    REFERENCES `enterprisewebapp`.`groups` (`idgroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_Product_Product1`
    FOREIGN KEY (`product_idProduct`)
    REFERENCES `enterprisewebapp`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`group_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`group_user` (
  `group_idgroup` INT NOT NULL,
  `user_id_user` INT NOT NULL,
  PRIMARY KEY (`group_idgroup`, `user_id_user`),
  INDEX `fk_group_has_User_User1_idx` (`user_id_user` ASC),
  INDEX `fk_group_has_User_group1_idx` (`group_idgroup` ASC),
  CONSTRAINT `fk_group_has_User_group1`
    FOREIGN KEY (`group_idgroup`)
    REFERENCES `enterprisewebapp`.`groups` (`idgroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_User_User1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `enterprisewebapp`.`History`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `enterprisewebapp`.`History` (
  `idHistory` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(400) NOT NULL,
  `User_id_user` INT NOT NULL,
  `history_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idHistory`, `User_id_user`),
  INDEX `fk_History_User1_idx` (`User_id_user` ASC),
  CONSTRAINT `fk_History_User1`
    FOREIGN KEY (`User_id_user`)
    REFERENCES `enterprisewebapp`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
